name: Deploy website to alys.phundrak.com
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Enable corepack and yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with VitePress
        run: yarn build
      - name: Deploy on the web
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: docs/.vitepress/dist/*
          target: ${{ secrets.DESTPATH }}
          strip_components: 3
